In [1]:
import pandas as pd
import numpy as np
import os

from ddf_utils.str import to_concept_id
from ddf_utils.index import create_index_file

In [2]:
codebook = 'source/Indicator_labels_for FLUDE.xlsx'

source_dir = 'source/'

In [3]:
cb = pd.read_excel(codebook)

In [5]:
cb.head()

,Topic,Indicator,Label,Unit of measure
0,FOREST AREA AND CHARACTERISTICS,Forest,Forest area,1 000 ha
1,FOREST AREA AND CHARACTERISTICS,Forchange,Change in total forest area,1 000 ha
2,FOREST AREA AND CHARACTERISTICS,ForPerc,Percent of land area with forest,%
3,FOREST AREA AND CHARACTERISTICS,PerCapFor,Forest area per capita,ha per person
4,FOREST AREA AND CHARACTERISTICS,NatFor,Natural forest area,1 000 ha

In [12]:
len(cb[['Topic', 'Indicator']].drop_duplicates())

150

In [11]:
len(cb['Indicator'].unique())

150

In [24]:
cb['Topic'].unique()

array(['FOREST AREA AND CHARACTERISTICS', 'PRODUCTION',
       'DISTURBARCE AND FOREST DEGRADATION',
       'MEASURING PROGRESS TOWARDS SFM', 'BIODIVERSITY AND CONSERVATION',
       'PROTECTIVE FUNCTIONS AND SELECTIVE ECOSYSTEM SERVICES',
       'ECONOMICS/LIVELIHOOD', 'OWNERSHIP', 'ANNUAL DATA'], dtype=object)

In [7]:
data = pd.read_csv('source/1.FOREST AREA AND CHARACTERISTICS.csv', encoding='iso-8859-1')

In [8]:
data

,Topic,Region,Country,Name,Year,TotPop1000,ToTArea,Incomes,Subregion,Domain,...,NatzedSpp,PlantFor,TSPlantFor,TTPlantFor,Pfchange,IntroSppPlant,Mangrove,TSMangrove,TTMangrove,PlantMan
0,1,NCA,ABW,Aruba,1990,62.148000,18,H,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.42,1.0,1.0,NaN
1,1,NCA,ABW,Aruba,2000,90.858000,18,H,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.42,1.0,1.0,NaN
2,1,NCA,ABW,Aruba,2005,100.031000,18,H,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.42,1.0,1.0,NaN
3,1,NCA,ABW,Aruba,2010,101.597000,18,H,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.42,1.0,1.0,NaN
4,1,NCA,ABW,Aruba,2015,109.293740,18,H,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.42,1.0,1.0,NaN
5,1,NCA,ABW,Aruba,9999,NaN,NaN,NaN,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
6,1,AS,AFG,Afghanistan,1990,11731.193000,"65,223.00",L,WCAsia,SubTrp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.00,1.0,1.0,0.0
7,1,AS,AFG,Afghanistan,2000,20595.360000,"65,223.00",L,WCAsia,SubTrp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.00,1.0,1.0,0.0
8,1,AS,AFG,Afghanistan,2005,24860.855000,"65,223.00",L,WCAsia,SubTrp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.00,1.0,1.0,0.0
9,1,AS,AFG,Afghanistan,2010,28397.812000,"65,223.00",L,WCAsia,SubTrp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.00,1.0,1.0,0.0
10,1,AS,AFG,Afghanistan,2015,36722.842530,"65,223.00",L,WCAsia,SubTrp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.00,1.0,1.0,0.0
11,1,AS,AFG,Afghanistan,9999,NaN,NaN,NaN,WCAsia,SubTrp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
12,1,AFR,AGO,Angola,1990,10333.844000,"124,670.00",UM,ESAfr,Trp,...,NaN,140.0,1.0,1.0,NaN,NaN,43.30,1.0,1.0,NaN
13,1,AFR,AGO,Angola,2000,13924.930000,"124,670.00",UM,ESAfr,Trp,...,NaN,134.0,1.0,1.0,-6.0,NaN,33.60,1.0,1.0,NaN
14,1,AFR,AGO,Angola,2005,16544.376000,"124,670.00",UM,ESAfr,Trp,...,NaN,131.0,1.0,1.0,-3.0,NaN,33.00,1.0,1.0,NaN
15,1,AFR,AGO,Angola,2010,19549.124000,"124,670.00",UM,ESAfr,Trp,...,NaN,128.0,1.0,1.0,-3.0,NaN,32.40,1.0,1.0,NaN
16,1,AFR,AGO,Angola,2015,21842.172920,"124,670.00",UM,ESAfr,Trp,...,NaN,125.0,1.0,1.0,-3.0,NaN,31.80,1.0,1.0,NaN
17,1,AFR,AGO,Angola,9999,NaN,NaN,NaN,ESAfr,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
18,1,NCA,AIA,Anguilla,1990,8.334000,9,NaN,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.09,1.0,1.0,NaN
19,1,NCA,AIA,Anguilla,2000,11.071000,9,NaN,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.09,1.0,1.0,NaN
20,1,NCA,AIA,Anguilla,2005,12.637000,9,NaN,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.09,1.0,1.0,NaN
21,1,NCA,AIA,Anguilla,2010,13.768000,9,NaN,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.09,1.0,1.0,NaN
22,1,NCA,AIA,Anguilla,2015,13.768000,9,NaN,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,0.09,1.0,1.0,NaN
23,1,NCA,AIA,Anguilla,9999,NaN,NaN,NaN,Carib,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
24,1,EU,ALB,Albania,1990,3446.882000,"2,874.80",UM,Europe,SubTrp,...,NaN,103.3,1.0,1.0,NaN,13.0,0.00,1.0,1.0,0.0
25,1,EU,ALB,Albania,2000,3304.948000,"2,875.30",UM,Europe,SubTrp,...,NaN,96.4,1.0,1.0,-6.9,4.9,0.00,1.0,1.0,0.0
26,1,EU,ALB,Albania,2005,3196.130000,"2,875.40",UM,Europe,SubTrp,...,NaN,98.2,1.0,1.0,1.8,5.5,0.00,1.0,1.0,0.0
27,1,EU,ALB,Albania,2010,3150.143000,"2,875.00",UM,Europe,SubTrp,...,NaN,94.0,1.0,1.0,-4.2,7.4,0.00,1.0,1.0,0.0
28,1,EU,ALB,Albania,2015,3260.217906,"2,875.00",UM,Europe,SubTrp,...,NaN,90.0,1.0,1.0,-4.0,NaN,0.00,1.0,1.0,0.0
29,1,EU,ALB,Albania,9999,NaN,NaN,NaN,Europe,SubTrp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,1,OCE,WSM,Samoa,1990,162.865000,284,LM,OCE,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
1375,1,OCE,WSM,Samoa,2000,174.614000,284,LM,OCE,Trp,...,NaN,32.1,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
1376,1,OCE,WSM,Samoa,2005,179.928000,284,LM,OCE,Trp,...,NaN,32.1,1.0,1.0,0.0,NaN,NaN,1.0,1.0,NaN
1377,1,OCE,WSM,Samoa,2010,186.029000,284,LM,OCE,Trp,...,NaN,32.1,1.0,1.0,0.0,NaN,NaN,1.0,1.0,NaN
1378,1,OCE,WSM,Samoa,2015,187.567387,284,LM,OCE,Trp,...,NaN,32.1,1.0,1.0,0.0,NaN,NaN,1.0,1.0,NaN
1379,1,OCE,WSM,Samoa,9999,NaN,NaN,NaN,OCE,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
1380,1,AS,YEM,Yemen,1990,11790.249000,"52,797.00",LM,WCAsia,Trp,...,NaN,0.0,1.0,1.0,NaN,0.0,0.95,1.0,1.0,NaN
1381,1,AS,YEM,Yemen,2000,17522.537000,"52,797.00",LM,WCAsia,Trp,...,NaN,0.0,1.0,1.0,0.0,0.0,0.90,1.0,1.0,NaN
1382,1,AS,YEM,Yemen,2005,20139.661000,"52,797.00",LM,WCAsia,Trp,...,NaN,0.0,1.0,1.0,0.0,0.0,0.90,1.0,1.0,NaN
1383,1,AS,YEM,Yemen,2010,22763.008000,"52,797.00",LM,WCAsia,Trp,...,NaN,0.0,1.0,1.0,0.0,0.0,0.90,1.0,1.0,NaN
1384,1,AS,YEM,Yemen,2015,27940.528530,"52,797.00",LM,WCAsia,Trp,...,NaN,0.0,1.0,1.0,0.0,0.0,0.90,1.0,1.0,NaN
1385,1,AS,YEM,Yemen,9999,NaN,NaN,NaN,WCAsia,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
1386,1,AFR,ZAF,South Africa,1990,36793.490000,"121,909.00",UM,ESAfr,Trp,...,NaN,1626.0,1.0,1.0,NaN,1626.0,2.40,1.0,1.0,0.0
1387,1,AFR,ZAF,South Africa,2000,44846.286000,"121,909.00",UM,ESAfr,Trp,...,NaN,1724.0,1.0,1.0,98.0,1724.0,2.40,1.0,1.0,0.0
1388,1,AFR,ZAF,South Africa,2005,48235.291000,"121,909.00",UM,ESAfr,Trp,...,NaN,1750.0,1.0,1.0,26.0,1750.0,2.40,1.0,1.0,0.0
1389,1,AFR,ZAF,South Africa,2010,51452.352000,"121,909.00",UM,ESAfr,Trp,...,NaN,1763.0,1.0,1.0,13.0,1763.0,2.40,1.0,1.0,0.0
1390,1,AFR,ZAF,South Africa,2015,51420.750940,"121,909.00",UM,ESAfr,Trp,...,NaN,1763.0,1.0,1.0,0.0,1763.0,2.40,1.0,1.0,0.0
1391,1,AFR,ZAF,South Africa,9999,NaN,NaN,UM,ESAfr,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN
1392,1,AFR,ZMB,Zambia,1990,7844.516000,"75,261.00",LM,ESAfr,Trp,...,NaN,60.0,2.0,1.0,NaN,NaN,0.00,3.0,3.0,0.0
1393,1,AFR,ZMB,Zambia,2000,10100.981000,"75,261.00",LM,ESAfr,Trp,...,NaN,60.0,2.0,1.0,0.0,NaN,0.00,3.0,3.0,0.0
1394,1,AFR,ZMB,Zambia,2005,11470.022000,"75,261.00",LM,ESAfr,Trp,...,NaN,60.0,2.0,1.0,0.0,NaN,0.00,3.0,3.0,0.0
1395,1,AFR,ZMB,Zambia,2010,13216.985000,"75,261.00",LM,ESAfr,Trp,...,NaN,62.0,2.0,1.0,2.0,NaN,0.00,3.0,3.0,0.0
1396,1,AFR,ZMB,Zambia,2015,15239.833110,"75,261.00",LM,ESAfr,Trp,...,NaN,64.0,2.0,1.0,2.0,NaN,0.00,3.0,3.0,0.0
1397,1,AFR,ZMB,Zambia,9999,NaN,NaN,LM,ESAfr,Trp,...,NaN,NaN,2.0,1.0,NaN,NaN,NaN,3.0,3.0,NaN
1398,1,AFR,ZWE,Zimbabwe,1990,10461.782000,"39,076.00",L,ESAfr,Trp,...,0.0,154.0,1.0,1.0,NaN,154.0,0.00,3.0,3.0,0.0
1399,1,AFR,ZWE,Zimbabwe,2000,12503.652000,"39,076.00",L,ESAfr,Trp,...,0.0,120.0,1.0,1.0,-34.0,120.0,0.00,3.0,3.0,0.0
1400,1,AFR,ZWE,Zimbabwe,2005,12710.589000,"39,076.00",L,ESAfr,Trp,...,0.0,108.0,1.0,1.0,-12.0,108.0,0.00,3.0,3.0,0.0
1401,1,AFR,ZWE,Zimbabwe,2010,13076.978000,"39,076.00",L,ESAfr,Trp,...,0.0,87.0,1.0,1.0,-21.0,87.0,0.00,3.0,3.0,0.0
1402,1,AFR,ZWE,Zimbabwe,2015,14002.615580,"39,076.00",L,ESAfr,Trp,...,0.0,87.0,1.0,1.0,0.0,87.0,0.00,3.0,3.0,0.0
1403,1,AFR,ZWE,Zimbabwe,9999,NaN,NaN,NaN,ESAfr,Trp,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,3.0,3.0,NaN

In [13]:
data.columns

Index(['Topic', 'Region', 'Country', 'Name', 'Year', 'TotPop1000', 'ToTArea',
       'Incomes', 'Subregion', 'Domain', 'ITTO', 'COMIFAC', 'FOREUR',
       'Montreal', 'UNECE', 'Forest', 'TSFor', 'TTFor', 'Forchange', 'ForPerc',
       'PerCapFor', 'NatFor', 'Nfchange', 'OthWooLan', 'TSOthWooLan',
       'TTOthWooLan', 'OthLan', 'LanTreCov', 'InWater', 'Landarea', 'ForExp',
       'TSForExp', 'TTForExp', ' Afforest', 'NatForExp', 'Deforest',
       'TSDeforest', 'TTDeforest', 'HumDef', 'Reforest', 'TSReforest',
       'TTReforest', 'ArtRef', 'PrimFor', 'TSPrimFor', 'TTPrimFor',
       'NatRegFor', 'TSNatRegFor', 'TTNatRegFor', 'IntroSpp', 'NatzedSpp',
       'PlantFor', 'TSPlantFor', 'TTPlantFor', 'Pfchange', 'IntroSppPlant',
       'Mangrove', 'TSMangrove', 'TTMangrove', 'PlantMan'],
      dtype='object')

In [121]:
all_data = []

for f in os.listdir(source_dir):
    if 'csv' in f:
        if f == '9. ANNUAL DATA.csv':
            df = pd.read_csv(os.path.join(source_dir, f), 
                             encoding='iso-8859-1', 
                             sep=';', decimal=',', 
                             skipinitialspace=True,
                             na_values=['n.a.', 'n/a']
                            )
        else:
            df = pd.read_csv(os.path.join(source_dir, f),
                             encoding='iso-8859-1', 
                             skipinitialspace=True,
                             na_values=['n.a.', 'n/a'],
                             thousands=','
                            )

        df = df.loc[:, 'Country':]
        
        all_data.append(df)

In [38]:
all_data[2]

,Country,Name,Year,TotPop1000,ToTArea,Incomes,Subregion,Domain.1,ITTO,COMIFAC,FOREUR,Montreal,UNECE,InvSppAreaToT,TSInvSppArea,TTInvSppArea,ReduCanopy,TTReduCanopy
0,ABW,Aruba,1990,62.148000,18,H,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
1,ABW,Aruba,2000,90.858000,18,H,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
2,ABW,Aruba,2005,100.031000,18,H,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
3,ABW,Aruba,2010,101.597000,18,H,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
4,ABW,Aruba,2015,109.293740,18,H,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
5,ABW,Aruba,9999,NaN,NaN,NaN,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
6,AFG,Afghanistan,1990,11731.193000,"65,223.00",L,WCAS,SubTrp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
7,AFG,Afghanistan,2000,20595.360000,"65,223.00",L,WCAS,SubTrp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
8,AFG,Afghanistan,2005,24860.855000,"65,223.00",L,WCAS,SubTrp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
9,AFG,Afghanistan,2010,28397.812000,"65,223.00",L,WCAS,SubTrp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
10,AFG,Afghanistan,2015,36722.842530,"65,223.00",L,WCAS,SubTrp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
11,AFG,Afghanistan,9999,NaN,NaN,NaN,WCAS,SubTrp,no,no,no,no,no,NaN,1.0,1.0,5.06,2.0
12,AGO,Angola,1990,10333.844000,"124,670.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
13,AGO,Angola,2000,13924.930000,"124,670.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
14,AGO,Angola,2005,16544.376000,"124,670.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
15,AGO,Angola,2010,19549.124000,"124,670.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
16,AGO,Angola,2015,21842.172920,"124,670.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
17,AGO,Angola,9999,NaN,NaN,NaN,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,1830.55,2.0
18,AIA,Anguilla,1990,8.334000,9,NaN,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
19,AIA,Anguilla,2000,11.071000,9,NaN,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
20,AIA,Anguilla,2005,12.637000,9,NaN,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
21,AIA,Anguilla,2010,13.768000,9,NaN,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
22,AIA,Anguilla,2015,13.768000,9,NaN,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
23,AIA,Anguilla,9999,NaN,NaN,NaN,Carib,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
24,ALB,Albania,1990,3446.882000,"2,874.80",UM,EU,SubTrp,no,no,no,no,yes,NaN,1.0,1.0,NaN,2.0
25,ALB,Albania,2000,3304.948000,"2,875.30",UM,EU,SubTrp,no,no,no,no,yes,NaN,1.0,1.0,NaN,2.0
26,ALB,Albania,2005,3196.130000,"2,875.40",UM,EU,SubTrp,no,no,no,no,yes,NaN,1.0,1.0,NaN,2.0
27,ALB,Albania,2010,3150.143000,"2,875.00",UM,EU,SubTrp,no,no,no,no,yes,NaN,1.0,1.0,NaN,2.0
28,ALB,Albania,2015,3260.217906,"2,875.00",UM,EU,SubTrp,no,no,no,no,yes,NaN,1.0,1.0,NaN,2.0
29,ALB,Albania,9999,NaN,NaN,NaN,EU,SubTrp,no,no,no,no,yes,NaN,1.0,1.0,22.69,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,WSM,Samoa,1990,162.865000,284,LM,OCE,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1375,WSM,Samoa,2000,174.614000,284,LM,OCE,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1376,WSM,Samoa,2005,179.928000,284,LM,OCE,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1377,WSM,Samoa,2010,186.029000,284,LM,OCE,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1378,WSM,Samoa,2015,187.567387,284,LM,OCE,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1379,WSM,Samoa,9999,NaN,NaN,NaN,OCE,Trp,no,no,no,no,no,NaN,NaN,NaN,35.18,2.0
1380,YEM,Yemen,1990,11790.249000,"52,797.00",LM,WCAS,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
1381,YEM,Yemen,2000,17522.537000,"52,797.00",LM,WCAS,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
1382,YEM,Yemen,2005,20139.661000,"52,797.00",LM,WCAS,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
1383,YEM,Yemen,2010,22763.008000,"52,797.00",LM,WCAS,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
1384,YEM,Yemen,2015,27940.528530,"52,797.00",LM,WCAS,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,2.0
1385,YEM,Yemen,9999,NaN,NaN,NaN,WCAS,Trp,no,no,no,no,no,NaN,1.0,1.0,0.00,2.0
1386,ZAF,South AFR,1990,36793.490000,"121,909.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,2.0,2.0,NaN,2.0
1387,ZAF,South AFR,2000,44846.286000,"121,909.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,2.0,2.0,NaN,2.0
1388,ZAF,South AFR,2005,48235.291000,"121,909.00",UM,ESAfr,Trp,no,no,no,no,no,12.0,2.0,2.0,NaN,2.0
1389,ZAF,South AFR,2010,51452.352000,"121,909.00",UM,ESAfr,Trp,no,no,no,no,no,86.0,2.0,2.0,NaN,2.0
1390,ZAF,South AFR,2015,51420.750940,"121,909.00",UM,ESAfr,Trp,no,no,no,no,no,NaN,2.0,2.0,NaN,2.0
1391,ZAF,South AFR,9999,NaN,NaN,UM,ESAfr,Trp,no,no,no,no,no,NaN,2.0,2.0,1266.95,2.0
1392,ZMB,Zambia,1990,7844.516000,"75,261.00",LM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1393,ZMB,Zambia,2000,10100.981000,"75,261.00",LM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1394,ZMB,Zambia,2005,11470.022000,"75,261.00",LM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1395,ZMB,Zambia,2010,13216.985000,"75,261.00",LM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1396,ZMB,Zambia,2015,15239.833110,"75,261.00",LM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,NaN,2.0
1397,ZMB,Zambia,9999,NaN,NaN,LM,ESAfr,Trp,no,no,no,no,no,NaN,NaN,NaN,1238.00,2.0
1398,ZWE,Zimbabwe,1990,10461.782000,"39,076.00",L,ESAfr,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
1399,ZWE,Zimbabwe,2000,12503.652000,"39,076.00",L,ESAfr,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
1400,ZWE,Zimbabwe,2005,12710.589000,"39,076.00",L,ESAfr,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
1401,ZWE,Zimbabwe,2010,13076.978000,"39,076.00",L,ESAfr,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
1402,ZWE,Zimbabwe,2015,14002.615580,"39,076.00",L,ESAfr,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN
1403,ZWE,Zimbabwe,9999,NaN,NaN,NaN,ESAfr,Trp,no,no,no,no,no,NaN,1.0,1.0,NaN,NaN

In [33]:
d9.iloc[370:380]

,Country,Year,Incomes,Subregion,Domain,WooRemov,WooFuel,BurnLan,BurnFor,FSCarea,PEFCarea,OthIntCertif,ForConvArea
370,AUT,2009,H,Europe,Temp,16727.438,4583.553,NaN,0.07,5.090,1956.0,0.0,NaN
371,AUT,2010,H,Europe,Temp,17830.955,4549.512,0.09,0.05,4.800,1956.0,0.0,NaN
372,AUT,2011,H,Europe,Temp,18695.671,5065.139,0.12,0.09,0.410,2384.0,0.0,NaN
373,AUT,2012,H,Europe,Temp,NaN,NaN,0.19,0.06,0.430,2650.0,0.0,NaN
374,AUT,2013,H,Europe,Temp,NaN,NaN,NaN,NaN,0.570,2741.0,NaN,0.0
375,AUT,2014,H,Europe,Temp,NaN,NaN,NaN,NaN,0.575,2782.0,NaN,NaN
376,AUT,2015,H,Europe,Temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,AUT,9999,H,Europe,Temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,AZE,1990,UM,WCAsia,Temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,AZE,1991,UM,WCAsia,Temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
# country

In [45]:
for df in all_data:
    print(len(df['Country'].drop_duplicates()))

234
234
234
234
234
234
234
234
234

In [50]:
country = all_data[0][['Country', 'Name']]

In [46]:
len(country.drop_duplicates())

234

In [51]:
country = country.drop_duplicates().copy()

In [52]:
country.columns = ['country', 'name']
country['country'] = country['country'].map(to_concept_id)

In [54]:
country.to_csv('../ddf--entities--country.csv', index=False)

In [55]:
# concepts

In [57]:
conc = cb[['Indicator', 'Label', 'Unit of measure']].copy()

In [59]:
conc.columns = ['concept', 'name', 'unit']

In [61]:
len(conc)

150

In [62]:
len(conc['concept'].map(to_concept_id).drop_duplicates())

150

In [63]:
conc['concept'] = conc['concept'].map(to_concept_id)
conc['concept_type'] = 'measure'

In [65]:
conc.to_csv('../ddf--concepts--continuous.csv', index=False)

In [66]:
disc = pd.DataFrame([['name', 'Name', 'string'], ['year', 'Year', 'time'],
                     ['country', 'Country', 'entity_domain'], ['unit', 'Unit', 'string']
                    ], columns=['concept', 'name', 'concept_type'])

In [68]:
disc.to_csv('../ddf--concepts--discrete.csv', index=False)

In [69]:
# datapoints

In [122]:
dps = {}


for df in all_data:
    df.columns = list(map(to_concept_id, df.columns))
    df['country'] = df['country'].map(to_concept_id)
    
    df = df.set_index(['country', 'year'])
    
    for c in df.columns:
        if c in conc['concept'].values:
            if c not in dps.keys():
                df_ = df[c].dropna().reset_index().copy()
                dps[c] = df_
                
            else:
                df_ = df[c].dropna().reset_index().copy()
                dps[c] = pd.concat([dps[c], df_]).drop_duplicates()

In [72]:
len(all_c)

153

In [74]:
all_c.sort()

In [78]:
t = pd.Series(all_c)

In [79]:
t[t.duplicated()]

42         fscarea
82    othintcertif
93        pefcarea
dtype: object

In [100]:
dps['fscarea'][dps['fscarea']['fscarea'] > 0]

     country  year    fscarea
50       arg  2005     77.920
51       arg  2010    449.840
74       aus  2005    511.140
75       aus  2010    602.730
80       aut  2005      7.770
81       aut  2010      4.800
98       bel  2005      6.170
99       bel  2010     14.690
123      bgr  2010    303.580
141      bih  2010    108.690
152      blr  2005    107.200
153      blr  2010   4080.000
158      blz  2005    104.890
159      blz  2010    104.890
170      bol  2005   1160.790
171      bol  2010   1744.090
175      bra  2000    638.410
176      bra  2005   3119.280
177      bra  2010   5169.330
211      can  2000     30.000
212      can  2005  15231.120
213      can  2010  40600.810
218      che  2005    652.079
219      che  2010    651.331
225      chl  2010    402.090
243      cmr  2010    705.060
255      cog  2010   1907.840
284      cri  2005     74.970
285      cri  2010     56.240
307      cze  2000     11.340
...      ...   ...        ...
6122     vnm  2010      9.780
6123     vnm  2011     15.640
6124     vnm  2012     41.340
6125     vnm  2013     49.010
6126     vnm  2014    136.706
6247     zaf  2000   1006.500
6248     zaf  2001   1006.500
6249     zaf  2002   1134.040
6250     zaf  2003   1637.390
6251     zaf  2004   1760.630
6252     zaf  2005   1720.730
6253     zaf  2006   1721.050
6254     zaf  2007   1551.470
6255     zaf  2008   1075.490
6256     zaf  2009   1678.540
6257     zaf  2010   2151.650
6258     zaf  2011   1744.400
6259     zaf  2012   1539.750
6260     zaf  2013   1544.885
6261     zaf  2014   1478.588
6277     zmb  2003      0.980
6278     zmb  2004      0.980
6303     zwe  2002    123.130
6304     zwe  2003    123.130
6305     zwe  2004    123.130
6306     zwe  2005    104.040
6307     zwe  2006    104.040
6308     zwe  2007    108.430
6309     zwe  2008    108.430
6310     zwe  2009     55.300

[1077 rows x 3 columns]

In [124]:
for k, df in dps.items():
    path = os.path.join('../', 'ddf--datapoints--{}--by--country--year.csv'.format(k))
    df.to_csv(path, index=False)

In [110]:
!open .

In [102]:
create_index_file('../')

,key,value,file
0,concept,name,ddf--concepts--continuous.csv
1,concept,unit,ddf--concepts--continuous.csv
2,concept,concept_type,ddf--concepts--continuous.csv
0,concept,name,ddf--concepts--discrete.csv
1,concept,concept_type,ddf--concepts--discrete.csv
0,"country,year",afforest,ddf--datapoints--afforest--by--country--year.csv
0,"country,year",artref,ddf--datapoints--artref--by--country--year.csv
0,"country,year",avalcont,ddf--datapoints--avalcont--by--country--year.csv
0,"country,year",biocons,ddf--datapoints--biocons--by--country--year.csv
0,"country,year",broagrow,ddf--datapoints--broagrow--by--country--year.csv
0,"country,year",burnfor,ddf--datapoints--burnfor--by--country--year.csv
0,"country,year",burnlan,ddf--datapoints--burnlan--by--country--year.csv
0,"country,year",carbstor,ddf--datapoints--carbstor--by--country--year.csv
0,"country,year",cleanwat,ddf--datapoints--cleanwat--by--country--year.csv
0,"country,year",commun,ddf--datapoints--commun--by--country--year.csv
0,"country,year",conifgrow,ddf--datapoints--conifgrow--by--country--year.csv
0,"country,year",consplan,ddf--datapoints--consplan--by--country--year.csv
0,"country,year",coststab,ddf--datapoints--coststab--by--country--year.csv
0,"country,year",cultserv,ddf--datapoints--cultserv--by--country--year.csv
0,"country,year",deadforcarb,ddf--datapoints--deadforcarb--by--country--yea...
0,"country,year",deadothcarb,ddf--datapoints--deadothcarb--by--country--yea...
0,"country,year",deforest,ddf--datapoints--deforest--by--country--year.csv
0,"country,year",desercont,ddf--datapoints--desercont--by--country--year.csv
0,"country,year",ecoserv,ddf--datapoints--ecoserv--by--country--year.csv
0,"country,year",expertestim1,ddf--datapoints--expertestim1--by--country--ye...
0,"country,year",expertestim2,ddf--datapoints--expertestim2--by--country--ye...
0,"country,year",femempl,ddf--datapoints--femempl--by--country--year.csv
0,"country,year",floodcont,ddf--datapoints--floodcont--by--country--year.csv
0,"country,year",forabovbiom,ddf--datapoints--forabovbiom--by--country--yea...
0,"country,year",forabovcarb,ddf--datapoints--forabovcarb--by--country--yea...
...,...,...,...
0,"country,year",pubpolicn,ddf--datapoints--pubpolicn--by--country--year.csv
0,"country,year",pubpolicp,ddf--datapoints--pubpolicp--by--country--year.csv
0,"country,year",pubpolicr,ddf--datapoints--pubpolicr--by--country--year.csv
0,"country,year",pubrecr,ddf--datapoints--pubrecr--by--country--year.csv
0,"country,year",reducanopy,ddf--datapoints--reducanopy--by--country--year...
0,"country,year",reforest,ddf--datapoints--reforest--by--country--year.csv
0,"country,year",revenue,ddf--datapoints--revenue--by--country--year.csv
0,"country,year",review,ddf--datapoints--review--by--country--year.csv
0,"country,year",sfmlegl,ddf--datapoints--sfmlegl--by--country--year.csv
0,"country,year",sfmlegn,ddf--datapoints--sfmlegn--by--country--year.csv
0,"country,year",sfmlegp,ddf--datapoints--sfmlegp--by--country--year.csv
0,"country,year",sfmlegr,ddf--datapoints--sfmlegr--by--country--year.csv
0,"country,year",sfmpolicl,ddf--datapoints--sfmpolicl--by--country--year.csv
0,"country,year",sfmpolicn,ddf--datapoints--sfmpolicn--by--country--year.csv
0,"country,year",sfmpolicp,ddf--datapoints--sfmpolicp--by--country--year.csv
0,"country,year",sfmpolicr,ddf--datapoints--sfmpolicr--by--country--year.csv
0,"country,year",social,ddf--datapoints--social--by--country--year.csv
0,"country,year",soilwatmanag,ddf--datapoints--soilwatmanag--by--country--ye...
0,"country,year",soilwatprot,ddf--datapoints--soilwatprot--by--country--yea...
0,"country,year",stateown,ddf--datapoints--stateown--by--country--year.csv
0,"country,year",staterepo,ddf--datapoints--staterepo--by--country--year.csv
0,"country,year",subgovown,ddf--datapoints--subgovown--by--country--year.csv
0,"country,year",unknown,ddf--datapoints--unknown--by--country--year.csv
0,"country,year",usdexp,ddf--datapoints--usdexp--by--country--year.csv
0,"country,year",usdforgrosval,ddf--datapoints--usdforgrosval--by--country--y...
0,"country,year",usdnwfp,ddf--datapoints--usdnwfp--by--country--year.csv
0,"country,year",usdrev,ddf--datapoints--usdrev--by--country--year.csv
0,"country,year",woofuel,ddf--datapoints--woofuel--by--country--year.csv
0,"country,year",wooremov,ddf--datapoints--wooremov--by--country--year.csv
0,country,name,ddf--entities--country.csv

In [128]:
conc = conc.set_index('concept')

In [129]:
for k, df in dps.items():
    if df[k].dtype == 'object':
        conc.loc[k, 'concept_type'] = 'string'

In [130]:
conc

,name,unit,concept_type
concept,,,
forest,Forest area,1 000 ha,measure
forchange,Change in total forest area,1 000 ha,string
forperc,Percent of land area with forest,%,measure
percapfor,Forest area per capita,ha per person,measure
natfor,Natural forest area,1 000 ha,measure
nfchange,Natural forest area change,1 000 ha,measure
othwoolan,Area of other wooded land,1 000 ha,measure
othlan,Area of other land,1 000 ha,measure
lantrecov,Other land of which with tree cover,1 000 ha,measure
inwater,Inland water bodies,1 000 ha,measure
landarea,Land area (without inland water),1 000 ha,measure
forexp,Forest expantion,ha/yr,measure
afforest,Forest expantion of which afforestion,ha/yr,measure
natforexp,Forest expantion of which natural expansion of...,ha/yr,measure
deforest,Deforestation,ha/yr,measure
humdef,Deforestation of which human induced,ha/yr,measure
reforest,Reforestation,ha/yr,measure
artref,Reforestation of which artificial,ha/yr,measure
primfor,Primary forest,1 000 ha,measure
natregfor,Other naturally regenerated forest,1 000 ha,measure
introspp,Other naturally regenerated forest of which in...,1 000 ha,measure
natzedspp,Other naturally regenerated forest of which na...,1 000 ha,measure
plantfor,Planted forest,1 000 ha,measure
pfchange,Planted forest area change,1 000 ha,measure
introsppplant,Planted forest of which is introduced species,1 000 ha,measure
mangrove,Area of mangrove forest,1 000 ha,measure
plantman,Area of mangrove forest of which planted,1 000 ha,measure
forgrow,Forest growing stock,Mill. m3,measure
conifgrow,Forest growing stock of which coniferous,Mill. m3,measure
broagrow,Forest growing stock of which broadleaved,Mill. m3,measure
...,...,...,...
revenue,Forest revenue,local currency,measure
pubforexpe,Public expenditure on forests,local currency,measure
forempl,Employment in forestry,1000 FTE,measure
femempl,Employment in forestry of which female,1000 FTE,measure
forgrosval,Gross value added from forestry,local currency,measure
usdnwfp,NWFP value in USD,USD,measure
usdrev,Revenue in USD,USD,measure
usdexp,Expenditure in USD,USD,measure
usdforgrosval,Gross value added in USD,USD,measure
pubown,Public ownership,1000 ha,measure
stateown,Public ownership of which owned by the state a...,1000 ha,measure
subgovown,Public ownership of which owned by the state a...,1000 ha,measure
privown,Private ownership,1000 ha,measure
indivown,Private ownership of which owned by individuals,1000 ha,measure
privbusown,Private ownership of which owned by private bu...,1000 ha,measure
indigown,"Private ownership of which owned by local, tri...",1000 ha,measure
unknown,Unknown ownership,1000 ha,measure
pubadmin,Public administration,1000 ha,measure
indiv,Individuals,1000 ha,measure
privcomp,Private companies,1000 ha,measure
commun,Communities,1000 ha,measure
other,Other,1000 ha,measure
wooremov,Total wood removal,1000 m3,measure
woofuel,Total wood removal of which wood fuel,1000 m3,measure
burnlan,Total land area burned,1 000 ha/yr,measure
burnfor,Total land area burned of which forest area bu...,1 000 ha/yr,measure
fscarea,Area of forest certified under FSC,1 000 ha,measure
pefcarea,Area of forest certified under PEFC,1 000 ha,measure
othintcertif,Area of forest certified by other internationa...,1 000 ha,measure
forconvarea,Forest area earmarked for conversion,1000 ha,measure

In [131]:
conc = conc.reset_index()

In [133]:
pd.concat([disc, conc]).to_csv('../ddf--co')

,concept,concept_type,name,unit
0,name,string,Name,NaN
1,year,time,Year,NaN
2,country,entity_domain,Country,NaN
3,unit,string,Unit,NaN
0,forest,measure,Forest area,1 000 ha
1,forchange,string,Change in total forest area,1 000 ha
2,forperc,measure,Percent of land area with forest,%
3,percapfor,measure,Forest area per capita,ha per person
4,natfor,measure,Natural forest area,1 000 ha
5,nfchange,measure,Natural forest area change,1 000 ha
6,othwoolan,measure,Area of other wooded land,1 000 ha
7,othlan,measure,Area of other land,1 000 ha
8,lantrecov,measure,Other land of which with tree cover,1 000 ha
9,inwater,measure,Inland water bodies,1 000 ha
10,landarea,measure,Land area (without inland water),1 000 ha
11,forexp,measure,Forest expantion,ha/yr
12,afforest,measure,Forest expantion of which afforestion,ha/yr
13,natforexp,measure,Forest expantion of which natural expansion of...,ha/yr
14,deforest,measure,Deforestation,ha/yr
15,humdef,measure,Deforestation of which human induced,ha/yr
16,reforest,measure,Reforestation,ha/yr
17,artref,measure,Reforestation of which artificial,ha/yr
18,primfor,measure,Primary forest,1 000 ha
19,natregfor,measure,Other naturally regenerated forest,1 000 ha
20,introspp,measure,Other naturally regenerated forest of which in...,1 000 ha
21,natzedspp,measure,Other naturally regenerated forest of which na...,1 000 ha
22,plantfor,measure,Planted forest,1 000 ha
23,pfchange,measure,Planted forest area change,1 000 ha
24,introsppplant,measure,Planted forest of which is introduced species,1 000 ha
25,mangrove,measure,Area of mangrove forest,1 000 ha
...,...,...,...,...
120,revenue,measure,Forest revenue,local currency
121,pubforexpe,measure,Public expenditure on forests,local currency
122,forempl,measure,Employment in forestry,1000 FTE
123,femempl,measure,Employment in forestry of which female,1000 FTE
124,forgrosval,measure,Gross value added from forestry,local currency
125,usdnwfp,measure,NWFP value in USD,USD
126,usdrev,measure,Revenue in USD,USD
127,usdexp,measure,Expenditure in USD,USD
128,usdforgrosval,measure,Gross value added in USD,USD
129,pubown,measure,Public ownership,1000 ha
130,stateown,measure,Public ownership of which owned by the state a...,1000 ha
131,subgovown,measure,Public ownership of which owned by the state a...,1000 ha
132,privown,measure,Private ownership,1000 ha
133,indivown,measure,Private ownership of which owned by individuals,1000 ha
134,privbusown,measure,Private ownership of which owned by private bu...,1000 ha
135,indigown,measure,"Private ownership of which owned by local, tri...",1000 ha
136,unknown,measure,Unknown ownership,1000 ha
137,pubadmin,measure,Public administration,1000 ha
138,indiv,measure,Individuals,1000 ha
139,privcomp,measure,Private companies,1000 ha
140,commun,measure,Communities,1000 ha
141,other,measure,Other,1000 ha
142,wooremov,measure,Total wood removal,1000 m3
143,woofuel,measure,Total wood removal of which wood fuel,1000 m3
144,burnlan,measure,Total land area burned,1 000 ha/yr
145,burnfor,measure,Total land area burned of which forest area bu...,1 000 ha/yr
146,fscarea,measure,Area of forest certified under FSC,1 000 ha
147,pefcarea,measure,Area of forest certified under PEFC,1 000 ha
148,othintcertif,measure,Area of forest certified by other internationa...,1 000 ha
149,forconvarea,measure,Forest area earmarked for conversion,1000 ha